[workspace]
members = [".", "cli"]
exclude = ["convert"]

[workspace.package]
version = "0.11.0-beta.4"
keywords = ["bitcoin", "wallet", "descriptor-wallet", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://lnp-bp.org"
repository = "https://github.com/BP-WG/bp-wallet"
rust-version = "1.70" # Due to clap
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.5.0"
strict_encoding = "2.6.1"
bp-std = "0.11.0-beta.3"
psbt = "0.11.0-beta.3"
descriptors = "0.11.0-beta.3"
bp-esplora = "0.11.0-beta.2"
serde_crate = { package = "serde", version = "1", features = ["derive"] }
serde_with = "3.4.0"
serde_yaml = "0.9.19"
toml = "0.8.2"
cfg_eval = "0.1.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

[package]
name = "bp-wallet"
version.workspace = true
description = "Modern, minimalistic & standard-compliant bitcoin wallet runtime"
keywords.workspace = true
categories.workspace = true
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "bpwallet"

[dependencies]
amplify = { workspace = true }
bp-std = { workspace = true }
bp-esplora = { workspace = true, optional = true }
psbt = { workspace = true }
descriptors = { workspace = true }
serde_crate = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
cfg_eval = { workspace = true, optional = true }

[features]
default = []
all = ["esplora", "fs"]
esplora = ["bp-esplora"]
fs = ["serde"]
serde = ["cfg_eval", "serde_crate", "serde_with", "serde_yaml", "toml", "bp-std/serde"]
